# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
install! 'cocoapods',
         :deterministic_uuids => false
target 'InvestmentCalculator' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InvestmentCalculator
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'

  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', 
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration',
    'ART'
  ]
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

end

